package com.samsung.prism.android.app.aidatacapture.constants

import java.time.Duration

object SharedPrefsConstants {

    const val FILE_TYPE= "filetype"
    const val TEXT_META_DATA_TYPE= "textmetadatatype"
    const val IS_LOGGED_IN="isLoggedIn"
    const val LANGUAGE_SELECTED="languageSelected"
    const val IS_FROM_LOGIN="isFromLogin"
    const val MOBILE_NUMBER="mobileNumber"
    const val IS_FROM_REGISTER="isFromRegister"
    const val USER="User"
    const val USER_EMAIL="userEmail"
    const val IS_ALL_AGREEMENT_UPLOADED="isAllAgreementUploaded"
    const val APPROVE_USER_EMAIL="approveUserEmail"
    const val AGREEMENT_URL="agreementUr"
    const val USER_FULL_NAME="userFullName"
    const val CATEGORY_NAME="categoryName"
    const val SUBCATEGORY_NAME="subCategoryName"
    const val HUMAN_AGREEMENT_NAME="humanAgreementName"
    const val LOCATION="location"
    const val SUB_LOCATION="subLocation"
    const val TIMING="timing"
    const val LIGHTING="lighting"
    const val MODEL="model"
    const val ORIENTATION="orientation"
    const val SCREEN_SIZE="screenSize"
    const val IS_IT_DSLR="dslr"
    const val CATEGORY="Category"
    const val IS_HUMAN_PRESENT="isHumanPresent"
    const val SELFIE="selfie"
    const val CHILDREN="children"
    const val CONSENT="consent"
    const val PROPS="props"
    const val IMAGE_TYPE="imageType"
    const val IS_FROM_METADATA="isFromHumanMetaData"
    const val DATA_MAJOR_CATEGORY="categoryString"
    const val IS_FROM_DASHBOARD="isFromDashboard"
    const val IS_LANGUAGE_SET="isLanguageSet"
    const val LANGUAGE =" language"
    const val CONTENT=" content"
    const val READABILITY="readability"
    const val CLARITY="clarity"
    const val VIEW_TYPE="viewType"
    const val SOURCE_DISTANCE = "sourceDistance"
    const val DEVICE = "device"
    const val NOISE ="noise"
    const val SOURCE= "source"
    const val SOURCE_MODEL = "sourceModel"
    const val DURATION ="duration"
    const val GENDER ="gender"
    const val AGE_GROUP ="ageGroup"
    const val LANGUAGES ="languages"
    const val MULTIPLE_SPEAKERS="multipleSpeakers"
    const val NOISE_OBJECT="noiseObject"
    const val MULTIPLE_NOISE= "multipleNoise"
    const val CONSENT_NAME ="ConsentName"
    const val CONSENT_EMAIL ="ConsentEmail"
    const val CONSENT_PLACE ="ConsentPlace"
    const val USER_MOBILE="UserMobile"
    const val IS_IT_USER_PROFILE="IsItUserProfile"
    const val TYPE= "type"
    const val PERSONALITY="personality"
    const val MOOD="mood"
    const val AGE="age"
    const val CLASS="class"
    const val NUMBERS = "numbers"
     const val MIXED_SOURCE =" mixedsource"
    const val STANDARD = "standard"
     const val TAG ="tag"
}